// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__app = []string{
"import express from \"express\";",
"import cors from 'cors';",
"",
"const app = express();",
"",
"app.use(",
"	cors({",
"		origin: ['origin(s)'],",
"		allowedHeaders: ['headers'],",
"	})",
");",
"		",
"app.use(express.json());",
"	",
"app.use('[path], [router]');",
"",
"export default app;",
}
