// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__client = []string{
"import { PrismaClient } from '@prisma/client';",
"",
"const client = new PrismaClient();",
"",
"export default client;",
}
