// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__exampleComponent = []string{
"import React from \"react\";",
"",
"const Example = () => {",
"  return <div>Example</div>;",
"};",
"",
"export default Example;",
}
