// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__expressClerkGlobal = []string{
"import express from \"express\";",
"",
"declare global {",
"  namespace Express {",
"    interface Request {",
"      auth: {",
"        userId: string;",
"      };",
"    }",
"  }",
"}",
}
