// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__expressFirebaseGlobal = []string{
"import express from \"express\";",
"",
"declare global {",
"  namespace Express {",
"    interface Request {",
"      user: {",
"        id: string;",
"        email: string;",
"      };",
"    }",
"  }",
"}",
}
