// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__firebaseAuthApp = []string{
"import express from \"express\";",
"import cors from \"cors\";",
"import authRouter from \"./lib/controllers/Auth/controller\";",
"import { requireAuth } from \"./utils/requireAuth\";",
"",
"const app = express();",
"",
"app.use(",
"	cors({",
"		origin: ['origin(s)'],",
"		allowedHeaders: ['Authorization', 'Content-Type'],",
"	})",
");",
"",
"app.use(express.json());",
"",
"app.use(\"/api/auth\", requireAuth, authRouter);",
"",
"export default app;",
}
