// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__firebaseGitignore = []string{
"# Node",
"node_modules",
"# Keep environment variables out of version control",
".env",
"",
"# Firebase",
"serviceAccountKey.json",
}
