// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__firebaseFrontTypes = []string{
"export type UserInputDto = {",
"  email: string;",
"  password: string;",
"};",
"",
"export type UserOutputDto = {",
"  id: string;",
"  email: string;",
"};",
}
