// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__index = []string{
"import app from './app';",
"",
"const PORT = 3009;",
"",
"app.listen(PORT, () => {",
"	console.log(`Server running on port ${PORT}`);",
"});",
}
