// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextFirebaseHook = []string{
"import { useContext } from 'react';",
"import { signInWithEmailAndPassword, signOut } from 'firebase/auth';",
"import { AuthContext } from '@/providers/AuthProvider';",
"import { auth } from '@/lib/firebase/config';",
"",
"export function useAuth() {",
"  const { user, loading } = useContext(AuthContext);",
"",
"  const login = (email: string, password: string) => {",
"    return signInWithEmailAndPassword(auth, email, password);",
"  };",
"",
"  const logout = () => {",
"    return signOut(auth);",
"  };",
"",
"  return { user, loading, login, logout };",
"}",
}
