// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextFirebaseMiddleware = []string{
"import { NextResponse } from 'next/server';",
"import type { NextRequest } from 'next/server';",
"",
"export function middleware(request: NextRequest) {",
"  const authToken = request.cookies.get('auth_token')?.value;",
"",
"  if (!authToken && request.nextUrl.pathname.startsWith('/dashboard')) {",
"    return NextResponse.redirect(new URL('/login', request.url));",
"  }",
"",
"  return NextResponse.next();",
"}",
"",
"export const config = {",
"  matcher: ['/dashboard/:path*'],",
"};",
}
