// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextFirebaseReadme = []string{
"// Next.js App with Firebase Integration",
"",
"## General",
"- You need to go to the firebase website and create a new project. Then add the project's serviceAccountKey to the serviceAccountKey file.",
"- Note that docker is running, it just isn't shown in the terminal",
"- If a file is in the gitignore but isn't greyed out, try the following:",
"    1. delete and then retype a letter of the filename in the gitignore, save the gitignore file.",
"    2. No luck? Reload the developer window.",
"    3. No luck? The .env is probably in the staging area of git. Unstage it.",
"    4. Still no luck? Look it up or ask for help. (sorry lol)",
"",
"- Note that a git repo has been initialized in the root directory of your project!",
"- IF USING SHADCN: to add a new component run `npx shadcn-ui@latest add <component_name>`",
"",
"#### Firebase",
"- You need to get your firebase config object from the Firebase console (your project on the firebase website) and add it to the .env file.",
"- Go look at the .env file to see what variables are needed.",
"",
"",
"## Resources",
"- Firebase: https://firebase.google.com/docs",
"- Next.js: https://nextjs.org/docs",
"- Docker: https://docs.docker.com/guides/",
"- Prisma: https://www.prisma.io/docs",
"- Tailwind: https://tailwindcss.com/docs",
"- DaisyUI: https://daisyui.com/docs",
"- Shadcn UI: https://ui.shadcn.com/docs",
"",
}
