// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextClerkReadme = []string{
"// Next.js App with clerk integration",
"",
"## General",
"- Note that docker is running, it just isn't shown in the terminal",
"- If a file is in the gitignore but isn't greyed out:",
"    1. delete and then retype a letter of the filename in the gitignore",
"    2. save the gitignore file, now the file should be greyed out",
"    3. if that doesn't work, reload the developer window",
"- Note that a git repo has been initialized in the root directory of your project!",
"",
"## Clerk",
"- You need to go to the clerk website and create a new project.",
"- Then add the project's publishable key and secret key to the .env.local file.",
}
