// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextClerkMiddleware = []string{
"import { clerkMiddleware } from \"@clerk/nextjs/server\";",
"",
"export default clerkMiddleware();",
"",
"export const config = {",
"  matcher: ['/((?!.*\\..*|_next).*)', '/', '/(api|trpc)(.*)'],",
"};",
}
