// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextFirebasePage = []string{
"import Link from 'next/link';",
"",
"export default function Home() {",
"  return (",
"    <div>",
"      <h1>Welcome to Next.js Firebase Prisma App</h1>",
"      <Link href=\"/login\">Login</Link>",
"    </div>",
"  );",
"}",
}
