// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextFirebaseDashboardPage = []string{
"'use client';",
"",
"import { useAuth } from '@/hooks/useAuth';",
"",
"export default function Dashboard() {",
"  const { user, logout } = useAuth();",
"",
"  return (",
"    <div>",
"      <h1>Welcome to your Dashboard</h1>",
"      <p>You are logged in as: {user?.email}</p>",
"      <button onClick={logout}>Logout</button>",
"    </div>",
"  );",
"}",
}
