// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__nextFirebaseLayout = []string{
"import { AuthProvider } from '@/components/AuthProvider';",
"",
"export default function RootLayout({",
"  children,",
"}: {",
"  children: React.ReactNode",
"}) {",
"  return (",
"    <html lang=\"en\">",
"      <body>",
"        <AuthProvider>",
"          {children}",
"        </AuthProvider>",
"      </body>",
"    </html>",
"  );",
"}",
}
