// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__noAuthService = []string{
"import axios from \"axios\";",
"import { UserInputDto } from \"./types\";",
"",
"const baseUrl: string = \"/api/users\";",
"",
"//...",
"",
"const example = async () => {",
"  try {",
"   ",
"  } catch (e) {",
"   ",
"  }",
"};",
"",
"//...",
"",
"export default { example };",
}
