// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__viteTsconfig = []string{
"{",
"  \"files\": [],",
"  \"references\": [",
"    {",
"      \"path\": \"./tsconfig.app.json\"",
"    },",
"    {",
"      \"path\": \"./tsconfig.node.json\"",
"    }",
"  ],",
"  \"compilerOptions\": {",
"    \"baseUrl\": \".\",",
"    \"paths\": {",
"      \"@/*\": [\"./src/*\"]",
"    }",
"  }",
"}",
}
