// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__viteClerkApp = []string{
"import { SignedIn, SignedOut, SignInButton, UserButton } from \"@clerk/clerk-react\";",
"",
"export default function App() {",
"  return (",
"    <header>",
"      <SignedOut>",
"        <SignInButton />",
"      </SignedOut>",
"      <SignedIn>",
"        <UserButton />",
"      </SignedIn>",
"    </header>",
"  )",
"}",
}
