// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__viteTailwindTconfig = []string{
"/** @type {import('tailwindcss').Config} */",
"export default {",
"  content: [\"./index.html\", \"./src/**/*.{js,ts,jsx,tsx}\"],",
"  theme: {",
"    extend: {},",
"  },",
"  plugins: [require(\"daisyui\")],",
"};",
}
