// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__viteComponentsJson = []string{
"{",
"  \"$schema\": \"https://ui.shadcn.com/schema.json\",",
"  \"style\": \"default\",",
"  \"rsc\": false,",
"  \"tsx\": true,",
"  \"tailwind\": {",
"    \"config\": \"tailwind.config.js\",",
"    \"css\": \"src/index.css\",",
"    \"baseColor\": \"neutral\",",
"    \"cssVariables\": false,",
"    \"prefix\": \"\"",
"  },",
"  \"aliases\": {",
"    \"components\": \"@/src/components/shadcn\",",
"    \"utils\": \"@/lib/utils\"",
"  }",
"}",
}
