// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

package generated

var File__viteShadcnUtils = []string{
"import { type ClassValue, clsx } from \"clsx\"",
"import { twMerge } from \"tailwind-merge\"",
"",
"export function cn(...inputs: ClassValue[]) {",
"  return twMerge(clsx(inputs))",
"}",
}
